services:
  - type: web
    name: prepeasy-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: ADMIN_EMAILS
        sync: false
      - key: ADMIN_INVITE_CODE
        sync: false
      - key: ADZUNA_APP_ID
        sync: false
      - key: ADZUNA_APP_KEY
        sync: false
      - key: ADZUNA_COUNTRY
        sync: false
